create extension if not exists pgcrypto;

create table if not exists public.usuarios (
  id uuid primary key references auth.users(id) on delete cascade,
  nombres text not null,
  correo text unique not null,
  usuario text unique not null,
  telefono text not null,
  rol text not null check (rol in ('admin', 'supervisor', 'chef', 'mesero')),
  activo boolean not null default true,
  latitud double precision not null default 0,
  longitud double precision not null default 0,
  fecha_registro timestamptz not null default now()
);

create table if not exists public.categorias_menu (
  id serial primary key,
  nombre text not null unique,
  orden int not null default 0
);

create table if not exists public.items_menu (
  id serial primary key,
  nombre text not null,
  descripcion text not null default '',
  precio numeric(10,2) not null,
  categoria_id int not null references public.categorias_menu(id),
  imagen_ref text not null default '',
  disponible boolean not null default true,
  activo boolean not null default true,
  fecha_creacion timestamptz not null default now(),
  fecha_actualizacion timestamptz not null default now()
);

create table if not exists public.pedidos (
  id uuid primary key default gen_random_uuid(),
  numero_pedido bigint generated by default as identity,
  mesero_id uuid references public.usuarios(id),
  chef_id uuid references public.usuarios(id),
  cliente text not null default 'Pedido app',
  mesa_o_direccion text not null default 'N/A',
  estado text not null check (estado in ('pendiente','en_preparacion','completado','cancelado')),
  origen text not null check (origen in ('app_mesero','api_externa')),
  total numeric(10,2) not null,
  notas text,
  timestamp_creacion timestamptz not null default now(),
  timestamp_completado timestamptz
);

create table if not exists public.pedido_items (
  id serial primary key,
  pedido_id uuid not null references public.pedidos(id) on delete cascade,
  item_menu_id int references public.items_menu(id),
  nombre_item_snapshot text not null,
  cantidad int not null,
  precio_unitario_snapshot numeric(10,2) not null,
  subtotal numeric(10,2) not null,
  notas text
);

create table if not exists public.transacciones (
  id uuid primary key default gen_random_uuid(),
  pedido_id uuid not null references public.pedidos(id) on delete cascade,
  monto numeric(10,2) not null,
  metodo_pago text not null default 'efectivo',
  fecha timestamptz not null default now()
);

alter table public.usuarios enable row level security;
alter table public.categorias_menu enable row level security;
alter table public.items_menu enable row level security;
alter table public.pedidos enable row level security;
alter table public.pedido_items enable row level security;
alter table public.transacciones enable row level security;

drop policy if exists "usuarios_select_auth" on public.usuarios;
create policy "usuarios_select_auth"
on public.usuarios
for select
to authenticated
using (true);

drop policy if exists "usuarios_insert_self_or_admin" on public.usuarios;
create policy "usuarios_insert_self_or_admin"
on public.usuarios
for insert
to authenticated
with check (
  auth.uid() = id
  or exists (
    select 1 from public.usuarios u
    where u.id = auth.uid() and u.rol = 'admin' and u.activo = true
  )
);

drop policy if exists "usuarios_update_admin" on public.usuarios;
create policy "usuarios_update_admin"
on public.usuarios
for update
to authenticated
using (
  exists (
    select 1 from public.usuarios u
    where u.id = auth.uid() and u.rol = 'admin' and u.activo = true
  )
)
with check (
  exists (
    select 1 from public.usuarios u
    where u.id = auth.uid() and u.rol = 'admin' and u.activo = true
  )
);

drop policy if exists "menu_select_auth" on public.items_menu;
create policy "menu_select_auth"
on public.items_menu
for select
to authenticated
using (activo = true);

drop policy if exists "menu_mutate_admin_supervisor" on public.items_menu;
create policy "menu_mutate_admin_supervisor"
on public.items_menu
for all
to authenticated
using (
  exists (
    select 1 from public.usuarios u
    where u.id = auth.uid()
      and u.activo = true
      and u.rol in ('admin', 'supervisor')
  )
)
with check (
  exists (
    select 1 from public.usuarios u
    where u.id = auth.uid()
      and u.activo = true
      and u.rol in ('admin', 'supervisor')
  )
);

drop policy if exists "pedidos_select_auth" on public.pedidos;
create policy "pedidos_select_auth"
on public.pedidos
for select
to authenticated
using (
  exists (select 1 from public.usuarios u where u.id = auth.uid() and u.rol in ('admin','supervisor','chef'))
  or mesero_id = auth.uid()
);

drop policy if exists "pedidos_insert_mesero" on public.pedidos;
create policy "pedidos_insert_mesero"
on public.pedidos
for insert
to authenticated
with check (
  mesero_id = auth.uid()
  and exists (
    select 1 from public.usuarios u
    where u.id = auth.uid()
      and u.rol in ('mesero', 'admin', 'supervisor')
      and u.activo = true
  )
);

drop policy if exists "pedidos_update_chef_admin" on public.pedidos;
create policy "pedidos_update_chef_admin"
on public.pedidos
for update
to authenticated
using (
  exists (
    select 1 from public.usuarios u
    where u.id = auth.uid()
      and u.rol in ('chef', 'admin', 'supervisor')
      and u.activo = true
  )
)
with check (
  exists (
    select 1 from public.usuarios u
    where u.id = auth.uid()
      and u.rol in ('chef', 'admin', 'supervisor')
      and u.activo = true
  )
);

drop policy if exists "pedido_items_select_auth" on public.pedido_items;
create policy "pedido_items_select_auth"
on public.pedido_items
for select
to authenticated
using (
  exists (
    select 1
    from public.pedidos p
    where p.id = pedido_id
      and (
        p.mesero_id = auth.uid()
        or exists (select 1 from public.usuarios u where u.id = auth.uid() and u.rol in ('admin','supervisor','chef'))
      )
  )
);

drop policy if exists "pedido_items_insert_auth" on public.pedido_items;
create policy "pedido_items_insert_auth"
on public.pedido_items
for insert
to authenticated
with check (
  exists (
    select 1
    from public.pedidos p
    where p.id = pedido_id
      and (
        p.mesero_id = auth.uid()
        or exists (select 1 from public.usuarios u where u.id = auth.uid() and u.rol in ('admin','supervisor'))
      )
  )
);
